# Sync dict.json / form_dict.json one-way from the MOD (single source of truth).
#
# STRICT RULE: never edit dict.json / form_dict.json on the mc-blueprint side.
#   Update the MOD side data/master/block/*.json instead
#   (form_dict.json is regenerated by `./gradlew runData`),
#   then run this script to reflect (MOD source -> mc-blueprint copy).
#   Bump the `version` field so copies can detect drift.
#   Details: obsidian rules/single-source.md
#
# Usage (PowerShell):  ./sync-from-mod.ps1   (use -ModRoot if auto-detect fails)
#
# NOTE: keep this file ASCII-only. Windows PowerShell 5.1 reads .ps1 as ANSI
#       when there is no BOM, so non-ASCII text would break parsing.

param([string]$ModRoot)

# Resolve the MOD data dir. If -ModRoot not given, auto-detect the MDK under C:\work
# (the folder name contains non-ASCII, so we search instead of hardcoding it).
if ($ModRoot) {
    $src = Join-Path $ModRoot "data\master\block"
} else {
    $src = Get-ChildItem "C:\work" -Directory -ErrorAction SilentlyContinue |
        ForEach-Object { Join-Path $_.FullName "forge-1.21.8-58.0.0-mdk\data\master\block" } |
        Where-Object { Test-Path $_ } | Select-Object -First 1
}
if (-not $src -or -not (Test-Path $src)) { Write-Error "MOD data dir not found (pass -ModRoot <mdk path>)"; exit 1 }

foreach ($f in @("dict.json", "form_dict.json")) {
    $from = Join-Path $src $f
    if (-not (Test-Path $from)) { Write-Error "not found: $from"; exit 1 }
    Copy-Item $from (Join-Path $PSScriptRoot $f) -Force
    Write-Host "synced $f  <-  $from"
}
Write-Host "done. index.html fetches ./dict.json at startup. Check the version display."
