# Sync dict.json / form_dict.json one-way from the MOD (single source of truth).
#
# STRICT RULE: never edit dict.json / form_dict.json on the mc-blueprint side.
#   Update the MOD side data/master/block/*.json instead
#   (form_dict.json is regenerated by `./gradlew runData`),
#   then run this script to reflect (MOD source -> mc-blueprint copy).
#   Bump the `version` field so copies can detect drift.
#   Details: obsidian rules/single-source.md
#
# Usage (PowerShell):  ./sync-from-mod.ps1   (use -ModRoot if auto-detect fails)
#
# NOTE: keep this file ASCII-only. Windows PowerShell 5.1 reads .ps1 as ANSI
#       when there is no BOM, so non-ASCII text would break parsing.

param([string]$ModRoot)

# Resolve the MOD data dir. If -ModRoot not given, auto-detect the MDK under C:\work
# (the folder name contains non-ASCII, so we search instead of hardcoding it).
if ($ModRoot) {
    $src = Join-Path $ModRoot "data\master\block"
} else {
    $src = Get-ChildItem "C:\work" -Directory -ErrorAction SilentlyContinue |
        ForEach-Object { Join-Path $_.FullName "forge-1.21.8-58.0.0-mdk\data\master\block" } |
        Where-Object { Test-Path $_ } | Select-Object -First 1
}
if (-not $src -or -not (Test-Path $src)) { Write-Error "MOD data dir not found (pass -ModRoot <mdk path>)"; exit 1 }

# dict.json (canonical, hand-edited form/mat single source).
foreach ($f in @("dict.json")) {
    $from = Join-Path $src $f
    if (-not (Test-Path $from)) { Write-Error "not found: $from"; exit 1 }
    Copy-Item $from (Join-Path $PSScriptRoot $f) -Force
    Write-Host "synced $f  <-  $from"
}

# blocks_all.json (block columns) + block_class_all.json (blockClass -> properties/settable).
# Generated out-of-game by `gradlew runData`; the ja column is updated in-game by /abtest exporttex.
foreach ($f in @("blocks_all.json", "block_class_all.json")) {
    $from = Join-Path $src $f
    if (Test-Path $from) {
        Copy-Item $from (Join-Path $PSScriptRoot $f) -Force
        Write-Host "synced $f  <-  $from"
    } else {
        Write-Host "skip $f (run gradlew runData to generate)"
    }
}

# Optional: block face textures (data/master/block/blocktex/*.png) -> assets/blocks/,
# plus the version-only file blocktex/version.json -> ./blocktex.json.
$texSrc = Join-Path $src "blocktex"
if (Test-Path $texSrc) {
    $texDst = Join-Path $PSScriptRoot "assets\blocks"
    if (-not (Test-Path $texDst)) { New-Item -ItemType Directory -Path $texDst -Force | Out-Null }
    # Clear stale pngs first (key scheme may change, e.g. MAT.png -> block_id.png).
    Get-ChildItem $texDst -Filter *.png -ErrorAction SilentlyContinue | Remove-Item -Force
    $pngs = Get-ChildItem $texSrc -Filter *.png -ErrorAction SilentlyContinue
    foreach ($p in $pngs) { Copy-Item $p.FullName (Join-Path $texDst $p.Name) -Force }
    Write-Host "synced $($pngs.Count) block textures  <-  $texSrc"
    $texVer = Join-Path $texSrc "version.json"
    if (Test-Path $texVer) {
        Copy-Item $texVer (Join-Path $PSScriptRoot "blocktex.json") -Force
        Write-Host "synced blocktex.json  <-  $texVer"
    }
} else {
    Write-Host "skip blocktex (run /abtest exporttex in-game to generate)"
}

Write-Host "done. index.html fetches ./dict.json at startup. Check the version display."
